version: '3.7'

services:
  database-dealership:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dealership
    container_name: db-dealership
    ports:
      - 5432:5432